In [1]:
import torch

In [8]:
t = torch.Tensor([[1, 0], [0, 1]])

In [9]:
t

tensor([[1., 0.],
        [0., 1.]])

In [10]:
t.long()

tensor([[1, 0],
        [0, 1]])

In [11]:
t.bool()

tensor([[ True, False],
        [False,  True]])

In [14]:
t[t == 1]

tensor([1., 1.])